/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './profile-edit.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './profile.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@ng-bootstrap/ng-bootstrap/modal/modal';
import * as import11 from './profile-edit.component.css.shim';
export class Wrapper_ProfileEditComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ProfileEditComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.ProfileEditComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ProfileEditComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ProfileEditComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ProfileEditComponent>;
  _ProfileEditComponent_0_3:Wrapper_ProfileEditComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ProfileEditComponent_Host0,renderType_ProfileEditComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-profile-edit',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ProfileEditComponent0(this.viewUtils,this,0,this._el_0);
    this._ProfileEditComponent_0_3 = new Wrapper_ProfileEditComponent(this.injectorGet(import8.ProfileService,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex),this.injectorGet(import10.NgbModal,this.parentIndex));
    this.compView_0.create(this._ProfileEditComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._ProfileEditComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ProfileEditComponent) && (0 === requestNodeIndex))) { return this._ProfileEditComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ProfileEditComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ProfileEditComponentNgFactory:import7.ComponentFactory<import0.ProfileEditComponent> = new import7.ComponentFactory<import0.ProfileEditComponent>('app-profile-edit',View_ProfileEditComponent_Host0,import0.ProfileEditComponent);
const styles_ProfileEditComponent:any[] = [import11.styles];
var renderType_ProfileEditComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_ProfileEditComponent,{});
export class View_ProfileEditComponent0 extends import1.AppView<import0.ProfileEditComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _text_74:any;
  _el_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  /*private*/ _expr_81:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ProfileEditComponent0,renderType_ProfileEditComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_81 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'div',new import3.InlineArray2(2,'class','col-lg-12'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'h1',new import3.InlineArray2(2,'class','page-header'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Edit your Portfolio Page\n        ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'small',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'NAMEHERE',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._text_12 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_13 = this.renderer.createText(this._el_3,'\n  ',(null as any));
    this._text_14 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','col-md-8'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n      ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'img',new import3.InlineArray8(6,'alt','','class','img-responsive','src','http://placehold.it/750x500'),(null as any));
    this._text_20 = this.renderer.createText(this._el_17,'\n    ',(null as any));
    this._text_21 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','col-md-4'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_22,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'',(null as any));
    this._text_26 = this.renderer.createText(this._el_22,'\n      glyphicon glyphicon-pencil\n      ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_22,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.',(null as any));
    this._text_29 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_22,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'Skills',(null as any));
    this._text_32 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_22,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n        ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_33,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'List Skills here as tags',(null as any));
    this._text_37 = this.renderer.createText(this._el_33,'\n      ',(null as any));
    this._text_38 = this.renderer.createText(this._el_22,'\n    ',(null as any));
    this._text_39 = this.renderer.createText(this._el_15,'\n  ',(null as any));
    this._text_40 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'\n    ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_41,'div',new import3.InlineArray2(2,'class','col-lg-12'),(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'\n      ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_43,'h3',new import3.InlineArray2(2,'class','page-header'),(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'NAMEHERE \'s Games',(null as any));
    this._text_47 = this.renderer.createText(this._el_43,'\n    ',(null as any));
    this._text_48 = this.renderer.createText(this._el_41,'\n    ',(null as any));
    this._text_49 = this.renderer.createText(this._el_41,'\n\n    ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_41,'div',new import3.InlineArray2(2,'class','col-sm-3 col-xs-6'),(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'\n      ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_50,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'\n        ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_52,'img',new import3.InlineArray8(6,'alt','','class','img-responsive portfolio-item','src','http://placehold.it/500x300'),(null as any));
    this._text_55 = this.renderer.createText(this._el_52,'\n      ',(null as any));
    this._text_56 = this.renderer.createText(this._el_50,'\n    ',(null as any));
    this._text_57 = this.renderer.createText(this._el_41,'\n\n    ',(null as any));
    this._text_58 = this.renderer.createText(this._el_41,'\n  ',(null as any));
    this._text_59 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_60 = import3.createRenderElement(this.renderer,this._el_0,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_61 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_0,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'Link your social accounts!',(null as any));
    this._text_64 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_65 = this.renderer.createText(this._el_0,'\n ',(null as any));
    this._text_66 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._el_67 = import3.createRenderElement(this.renderer,this._el_0,'button',new import3.InlineArray2(2,'class','btn btn-lg btn-outline-primary'),(null as any));
    this._text_68 = this.renderer.createText(this._el_67,'Link Facebook',(null as any));
    this._text_69 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_0,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_71 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._el_72 = import3.createRenderElement(this.renderer,this._el_0,'button',new import3.InlineArray2(2,'class','btn btn-lg btn-outline-primary'),(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'Link Github',(null as any));
    this._text_74 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._el_75 = import3.createRenderElement(this.renderer,this._el_0,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_76 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._el_77 = import3.createRenderElement(this.renderer,this._el_0,'button',new import3.InlineArray2(2,'class','btn btn-lg btn-outline-primary'),(null as any));
    this._text_78 = this.renderer.createText(this._el_77,'Link LinkedIn',(null as any));
    this._text_79 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_80 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_52,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_52));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_67,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_67));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_72,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_72));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_77,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_77));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._text_80
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_81:any = import3.inlineInterpolate(1,'Snippit\'s of ',this.context.user,'');
    if (import3.checkBinding(throwOnChange,this._expr_81,currVal_81)) {
      this.renderer.setText(this._text_25,currVal_81);
      this._expr_81 = currVal_81;
    }
  }
  handleEvent_52(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.useJwtHelper()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_67(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.linkFacebook()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_72(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.linkGithub()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_77(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.linkLinkedin()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}