/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.works[_ngcontent-%COMP%] {\n  padding-bottom: 15px;\n  border-style: ridge;\n  border-color: grey;\n  border-width: thin;\n}\n\n.work-img[_ngcontent-%COMP%] {\n  \n}'];