/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './work-details.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './profile.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from './work-details.component.css.shim';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import13 from '@angular/core/src/linker/template_ref';
import * as import14 from '@angular/common/src/directives/ng_if';
import * as import15 from '../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import16 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import17 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import18 from '../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from '@angular/forms/src/directives/default_value_accessor';
import * as import21 from '@angular/forms/src/directives/control_value_accessor';
import * as import22 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import23 from '@angular/forms/src/directives/ng_control';
import * as import24 from '@angular/forms/src/directives/ng_control_status';
import * as import25 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import26 from '@angular/forms/src/directives/control_container';
export class Wrapper_WorkDetailsComponent {
  /*private*/ _eventHandler:Function;
  context:import0.WorkDetailsComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.WorkDetailsComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_WorkDetailsComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_WorkDetailsComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.WorkDetailsComponent>;
  _WorkDetailsComponent_0_3:Wrapper_WorkDetailsComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_WorkDetailsComponent_Host0,renderType_WorkDetailsComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-work-details',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_WorkDetailsComponent0(this.viewUtils,this,0,this._el_0);
    this._WorkDetailsComponent_0_3 = new Wrapper_WorkDetailsComponent(this.injectorGet(import8.ProfileService,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex));
    this.compView_0.create(this._WorkDetailsComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._WorkDetailsComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.WorkDetailsComponent) && (0 === requestNodeIndex))) { return this._WorkDetailsComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._WorkDetailsComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const WorkDetailsComponentNgFactory:import7.ComponentFactory<import0.WorkDetailsComponent> = new import7.ComponentFactory<import0.WorkDetailsComponent>('app-work-details',View_WorkDetailsComponent_Host0,import0.WorkDetailsComponent);
const styles_WorkDetailsComponent:any[] = [import10.styles];
var renderType_WorkDetailsComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_WorkDetailsComponent,{});
export class View_WorkDetailsComponent0 extends import1.AppView<import0.WorkDetailsComponent> {
  _anchor_0:any;
  /*private*/ _vc_0:import11.ViewContainer;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import12.Wrapper_NgIf;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_WorkDetailsComponent0,renderType_WorkDetailsComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_0 = new import11.ViewContainer(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import13.TemplateRef_(this,0,this._anchor_0);
    this._NgIf_0_6 = new import12.Wrapper_NgIf(this._vc_0.vcRef,this._TemplateRef_0_5);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._anchor_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import14.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.user;
    this._NgIf_0_6.check_ngIf(currVal_0_0_0,throwOnChange,false);
    this._NgIf_0_6.ngDoCheck(this,this._anchor_0,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 0)) { return new View_WorkDetailsComponent1(this.viewUtils,this,0,this._anchor_0,this._vc_0); }
    return (null as any);
  }
}
class View_WorkDetailsComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _FormGroupDirective_5_3:import15.Wrapper_FormGroupDirective;
  _ControlContainer_5_4:any;
  _NgControlStatusGroup_5_5:import16.Wrapper_NgControlStatusGroup;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _DefaultValueAccessor_12_3:import17.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_12_4:any[];
  _FormControlName_12_5:import18.Wrapper_FormControlName;
  _NgControl_12_6:any;
  _NgControlStatus_12_7:import16.Wrapper_NgControlStatus;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _DefaultValueAccessor_17_3:import17.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_17_4:any[];
  _FormControlName_17_5:import18.Wrapper_FormControlName;
  _NgControl_17_6:any;
  _NgControlStatus_17_7:import16.Wrapper_NgControlStatus;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _DefaultValueAccessor_22_3:import17.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_22_4:any[];
  _FormControlName_22_5:import18.Wrapper_FormControlName;
  _NgControl_22_6:any;
  _NgControlStatus_22_7:import16.Wrapper_NgControlStatus;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _DefaultValueAccessor_27_3:import17.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_27_4:any[];
  _FormControlName_27_5:import18.Wrapper_FormControlName;
  _NgControl_27_6:any;
  _NgControlStatus_27_7:import16.Wrapper_NgControlStatus;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  /*private*/ _expr_57:any;
  /*private*/ _expr_58:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_WorkDetailsComponent1,renderType_WorkDetailsComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_57 = import6.UNINITIALIZED;
    this._expr_58 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._FormGroupDirective_5_3 = new import15.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_5_4 = this._FormGroupDirective_5_3.context;
    this._NgControlStatusGroup_5_5 = new import16.Wrapper_NgControlStatusGroup(this._ControlContainer_5_4);
    this._text_6 = this.renderer.createText(this._el_5,'\n  ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'label',new import3.InlineArray2(2,'for','title'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'Title',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_7,'input',new import3.InlineArray16(10,'class','form-control','formControlName','title','id','title','placeholder','work title here','type','text'),(null as any));
    this._DefaultValueAccessor_12_3 = new import17.Wrapper_DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_12));
    this._NG_VALUE_ACCESSOR_12_4 = [this._DefaultValueAccessor_12_3.context];
    this._FormControlName_12_5 = new import18.Wrapper_FormControlName(this._ControlContainer_5_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_12_4);
    this._NgControl_12_6 = this._FormControlName_12_5.context;
    this._NgControlStatus_12_7 = new import16.Wrapper_NgControlStatus(this._NgControl_12_6);
    this._text_13 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_7,'label',new import3.InlineArray2(2,'for','description'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'Description',(null as any));
    this._text_16 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_7,'textarea',new import3.InlineArray16(10,'class','form-control','formControlName','description','id','description','placeholder','work description here','rows','4'),(null as any));
    this._DefaultValueAccessor_17_3 = new import17.Wrapper_DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_17));
    this._NG_VALUE_ACCESSOR_17_4 = [this._DefaultValueAccessor_17_3.context];
    this._FormControlName_17_5 = new import18.Wrapper_FormControlName(this._ControlContainer_5_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_17_4);
    this._NgControl_17_6 = this._FormControlName_17_5.context;
    this._NgControlStatus_17_7 = new import16.Wrapper_NgControlStatus(this._NgControl_17_6);
    this._text_18 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_7,'label',new import3.InlineArray2(2,'for','url'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Link',(null as any));
    this._text_21 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_7,'input',new import3.InlineArray16(10,'class','form-control','formControlName','url','id','url','placeholder','work url here','type','text'),(null as any));
    this._DefaultValueAccessor_22_3 = new import17.Wrapper_DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_22));
    this._NG_VALUE_ACCESSOR_22_4 = [this._DefaultValueAccessor_22_3.context];
    this._FormControlName_22_5 = new import18.Wrapper_FormControlName(this._ControlContainer_5_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_22_4);
    this._NgControl_22_6 = this._FormControlName_22_5.context;
    this._NgControlStatus_22_7 = new import16.Wrapper_NgControlStatus(this._NgControl_22_6);
    this._text_23 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_7,'label',new import3.InlineArray2(2,'for','video'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'Youtube Link',(null as any));
    this._text_26 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_7,'input',new import3.InlineArray16(10,'class','form-control','formControlName','video','id','video','placeholder','work video here','type','text'),(null as any));
    this._DefaultValueAccessor_27_3 = new import17.Wrapper_DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_27));
    this._NG_VALUE_ACCESSOR_27_4 = [this._DefaultValueAccessor_27_3.context];
    this._FormControlName_27_5 = new import18.Wrapper_FormControlName(this._ControlContainer_5_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_27_4);
    this._NgControl_27_6 = this._FormControlName_27_5.context;
    this._NgControlStatus_27_7 = new import16.Wrapper_NgControlStatus(this._NgControl_27_6);
    this._text_28 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_7,'button',new import3.InlineArray4(4,'class','btn btn-lg btn-outline-primary','type','submit'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'Submit',(null as any));
    this._text_31 = this.renderer.createText(this._el_7,'\n  ',(null as any));
    this._text_32 = this.renderer.createText(this._el_5,'\n',(null as any));
    this._text_33 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_5));
    this._FormGroupDirective_5_3.subscribe(this,this.eventHandler(this.handleEvent_5),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_12,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_12));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_17,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_17));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_22,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_22));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_27,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_27));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.DefaultValueAccessor) && (12 === requestNodeIndex))) { return this._DefaultValueAccessor_12_3.context; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (12 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_12_4; }
    if (((token === import22.FormControlName) && (12 === requestNodeIndex))) { return this._FormControlName_12_5.context; }
    if (((token === import23.NgControl) && (12 === requestNodeIndex))) { return this._NgControl_12_6; }
    if (((token === import24.NgControlStatus) && (12 === requestNodeIndex))) { return this._NgControlStatus_12_7.context; }
    if (((token === import20.DefaultValueAccessor) && (17 === requestNodeIndex))) { return this._DefaultValueAccessor_17_3.context; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (17 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_17_4; }
    if (((token === import22.FormControlName) && (17 === requestNodeIndex))) { return this._FormControlName_17_5.context; }
    if (((token === import23.NgControl) && (17 === requestNodeIndex))) { return this._NgControl_17_6; }
    if (((token === import24.NgControlStatus) && (17 === requestNodeIndex))) { return this._NgControlStatus_17_7.context; }
    if (((token === import20.DefaultValueAccessor) && (22 === requestNodeIndex))) { return this._DefaultValueAccessor_22_3.context; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (22 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_22_4; }
    if (((token === import22.FormControlName) && (22 === requestNodeIndex))) { return this._FormControlName_22_5.context; }
    if (((token === import23.NgControl) && (22 === requestNodeIndex))) { return this._NgControl_22_6; }
    if (((token === import24.NgControlStatus) && (22 === requestNodeIndex))) { return this._NgControlStatus_22_7.context; }
    if (((token === import20.DefaultValueAccessor) && (27 === requestNodeIndex))) { return this._DefaultValueAccessor_27_3.context; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (27 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_27_4; }
    if (((token === import22.FormControlName) && (27 === requestNodeIndex))) { return this._FormControlName_27_5.context; }
    if (((token === import23.NgControl) && (27 === requestNodeIndex))) { return this._NgControl_27_6; }
    if (((token === import24.NgControlStatus) && (27 === requestNodeIndex))) { return this._NgControlStatus_27_7.context; }
    if (((token === import25.FormGroupDirective) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._FormGroupDirective_5_3.context; }
    if (((token === import26.ControlContainer) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._ControlContainer_5_4; }
    if (((token === import24.NgControlStatusGroup) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._NgControlStatusGroup_5_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5_0_0:any = this.parentView.context.worksForm;
    this._FormGroupDirective_5_3.check_form(currVal_5_0_0,throwOnChange,false);
    this._FormGroupDirective_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    this._NgControlStatusGroup_5_5.ngDoCheck(this,this._el_5,throwOnChange);
    this._DefaultValueAccessor_12_3.ngDoCheck(this,this._el_12,throwOnChange);
    const currVal_12_1_0:any = 'title';
    this._FormControlName_12_5.check_name(currVal_12_1_0,throwOnChange,false);
    this._FormControlName_12_5.ngDoCheck(this,this._el_12,throwOnChange);
    this._NgControlStatus_12_7.ngDoCheck(this,this._el_12,throwOnChange);
    this._DefaultValueAccessor_17_3.ngDoCheck(this,this._el_17,throwOnChange);
    const currVal_17_1_0:any = 'description';
    this._FormControlName_17_5.check_name(currVal_17_1_0,throwOnChange,false);
    this._FormControlName_17_5.ngDoCheck(this,this._el_17,throwOnChange);
    this._NgControlStatus_17_7.ngDoCheck(this,this._el_17,throwOnChange);
    this._DefaultValueAccessor_22_3.ngDoCheck(this,this._el_22,throwOnChange);
    const currVal_22_1_0:any = 'url';
    this._FormControlName_22_5.check_name(currVal_22_1_0,throwOnChange,false);
    this._FormControlName_22_5.ngDoCheck(this,this._el_22,throwOnChange);
    this._NgControlStatus_22_7.ngDoCheck(this,this._el_22,throwOnChange);
    this._DefaultValueAccessor_27_3.ngDoCheck(this,this._el_27,throwOnChange);
    const currVal_27_1_0:any = 'video';
    this._FormControlName_27_5.check_name(currVal_27_1_0,throwOnChange,false);
    this._FormControlName_27_5.ngDoCheck(this,this._el_27,throwOnChange);
    this._NgControlStatus_27_7.ngDoCheck(this,this._el_27,throwOnChange);
    const currVal_57:any = import3.inlineInterpolate(1,'',this.parentView.context.user.firstName,'');
    if (import3.checkBinding(throwOnChange,this._expr_57,currVal_57)) {
      this.renderer.setText(this._text_3,currVal_57);
      this._expr_57 = currVal_57;
    }
    this._NgControlStatusGroup_5_5.checkHost(this,this,this._el_5,throwOnChange);
    this._NgControlStatus_12_7.checkHost(this,this,this._el_12,throwOnChange);
    this._NgControlStatus_17_7.checkHost(this,this,this._el_17,throwOnChange);
    this._NgControlStatus_22_7.checkHost(this,this,this._el_22,throwOnChange);
    this._NgControlStatus_27_7.checkHost(this,this,this._el_27,throwOnChange);
    const currVal_58:boolean = !this.parentView.context.worksForm.valid;
    if (import3.checkBinding(throwOnChange,this._expr_58,currVal_58)) {
      this.renderer.setElementProperty(this._el_29,'disabled',currVal_58);
      this._expr_58 = currVal_58;
    }
  }
  destroyInternal():void {
    this._FormControlName_12_5.ngOnDestroy();
    this._FormControlName_17_5.ngOnDestroy();
    this._FormControlName_22_5.ngOnDestroy();
    this._FormControlName_27_5.ngOnDestroy();
    this._FormGroupDirective_5_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_5_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.parentView.context.submitWork()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_12(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_12_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_17(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_17_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_22(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_22_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_27(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_27_3.handleEvent(eventName,$event) && result);
    return result;
  }
}