/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.my-drop-zone[_ngcontent-%COMP%] {\r\n  border: dotted 3px lightgray;\r\n}\r\n.nv-file-over[_ngcontent-%COMP%] {\r\n  border: dotted 3px red;\r\n}\r\n\r\n.another-file-over-class[_ngcontent-%COMP%] {\r\n  border: dotted 3px green;\r\n}\r\n\r\n.modal-content[_ngcontent-%COMP%] {\r\n  height: 900px;\r\n  \r\n}\r\n\r\nbody[_ngcontent-%COMP%], html[_ngcontent-%COMP%] {\r\n  height: 100%;\r\n}'];