/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './header.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../auth/auth.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from './header.component.css.shim';
import * as import11 from '../../../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import12 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/dropdown/dropdown.ngfactory';
import * as import13 from '../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import14 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import15 from '@angular/core/src/linker/view_container';
import * as import16 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import17 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import18 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown-config';
import * as import21 from '@angular/core/src/linker/template_ref';
import * as import22 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown';
import * as import23 from '@angular/forms/src/directives/ng_form';
import * as import24 from '@angular/forms/src/directives/control_container';
import * as import25 from '@angular/forms/src/directives/ng_control_status';
import * as import26 from '@angular/common/src/directives/ng_if';
import * as import27 from '@angular/common/src/directives/ng_class';
export class Wrapper_HeaderComponent {
  /*private*/ _eventHandler:Function;
  context:import0.HeaderComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.HeaderComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_HeaderComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_HeaderComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.HeaderComponent>;
  _HeaderComponent_0_3:Wrapper_HeaderComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HeaderComponent_Host0,renderType_HeaderComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-header',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_HeaderComponent0(this.viewUtils,this,0,this._el_0);
    this._HeaderComponent_0_3 = new Wrapper_HeaderComponent(this.injectorGet(import8.AuthService,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex));
    this.compView_0.create(this._HeaderComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._HeaderComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HeaderComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const HeaderComponentNgFactory:import7.ComponentFactory<import0.HeaderComponent> = new import7.ComponentFactory<import0.HeaderComponent>('app-header',View_HeaderComponent_Host0,import0.HeaderComponent);
const styles_HeaderComponent:any[] = [import10.styles];
var renderType_HeaderComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_HeaderComponent,{});
export class View_HeaderComponent0 extends import1.AppView<import0.HeaderComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _NgClass_22_3:import11.Wrapper_NgClass;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _NgbDropdown_36_3:import12.Wrapper_NgbDropdown;
  _text_37:any;
  _el_38:any;
  _NgbDropdownToggle_38_3:import12.Wrapper_NgbDropdownToggle;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _el_52:any;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _el_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _el_63:any;
  _el_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  _NgForm_70_3:import13.Wrapper_NgForm;
  _ControlContainer_70_4:any;
  _NgControlStatusGroup_70_5:import14.Wrapper_NgControlStatusGroup;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _el_81:any;
  _text_82:any;
  _el_83:any;
  _anchor_84:any;
  /*private*/ _vc_84:import15.ViewContainer;
  _TemplateRef_84_5:any;
  _NgIf_84_6:import16.Wrapper_NgIf;
  _text_85:any;
  _anchor_86:any;
  /*private*/ _vc_86:import15.ViewContainer;
  _TemplateRef_86_5:any;
  _NgIf_86_6:import16.Wrapper_NgIf;
  _text_87:any;
  _text_88:any;
  _text_89:any;
  _text_90:any;
  _text_91:any;
  _map_104:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HeaderComponent0,renderType_HeaderComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._map_104 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {in: p0};
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'nav',new import3.InlineArray2(2,'class','navbar navbar-default'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','navbar-header'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'button',new import3.InlineArray16(10,'aria-expanded','false','class','navbar-toggle collapsed','data-target','#navbar-mobile-collapse','data-toggle','collapse','type','button'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'span',new import3.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Toggle navigation',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_6,'span',new import3.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_12 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_6,'span',new import3.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_14 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_6,'span',new import3.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_16 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_4,'a',new import3.InlineArray4(4,'class','navbar-brand','href','#'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'Brand',(null as any));
    this._text_20 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_21 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray4(4,'class','collapse navbar-collapse','id','navbar-mobile-collapse'),(null as any));
    this._NgClass_22_3 = new import11.Wrapper_NgClass(this.parentView.injectorGet(import17.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import18.KeyValueDiffers,this.parentIndex),new import19.ElementRef(this._el_22),this.renderer);
    this._text_23 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_22,'ul',new import3.InlineArray2(2,'class','nav navbar-nav'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'li',new import3.InlineArray2(2,'class','active'),(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_26,'a',new import3.InlineArray2(2,'href','/news'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'News ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'span',new import3.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'(current)',(null as any));
    this._text_31 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_24,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_32,'a',new import3.InlineArray2(2,'href','/games'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'Games',(null as any));
    this._text_35 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_24,'li',new import3.InlineArray4(4,'class','dropdown','ngbDropdown',''),(null as any));
    this._NgbDropdown_36_3 = new import12.Wrapper_NgbDropdown(this.parentView.injectorGet(import20.NgbDropdownConfig,this.parentIndex));
    this._text_37 = this.renderer.createText(this._el_36,'\n          ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_36,'a',new import3.InlineArray16(12,'aria-expanded','false','aria-haspopup','true','class','dropdown-toggle dropdown-toggle','data-toggle','dropdown','ngbDropdownToggle','','role','button'),(null as any));
    this._NgbDropdownToggle_38_3 = new import12.Wrapper_NgbDropdownToggle(this._NgbDropdown_36_3.context,new import19.ElementRef(this._el_38));
    this._text_39 = this.renderer.createText(this._el_38,'Dropdown ',(null as any));
    this._text_40 = this.renderer.createText(this._el_36,'\n          ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_36,'ul',new import3.InlineArray2(2,'class','dropdown-menu'),(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'\n            ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_41,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_43,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'Action',(null as any));
    this._text_46 = this.renderer.createText(this._el_41,'\n            ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_41,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_47,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'Another action',(null as any));
    this._text_50 = this.renderer.createText(this._el_41,'\n            ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_41,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_51,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'Something else here',(null as any));
    this._text_54 = this.renderer.createText(this._el_41,'\n            ',(null as any));
    this._el_55 = import3.createRenderElement(this.renderer,this._el_41,'li',new import3.InlineArray4(4,'class','divider','role','separator'),(null as any));
    this._text_56 = this.renderer.createText(this._el_41,'\n            ',(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_41,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_57,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'Separated link',(null as any));
    this._text_60 = this.renderer.createText(this._el_41,'\n            ',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,this._el_41,'li',new import3.InlineArray4(4,'class','divider','role','separator'),(null as any));
    this._text_62 = this.renderer.createText(this._el_41,'\n            ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_41,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_64 = import3.createRenderElement(this.renderer,this._el_63,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_65 = this.renderer.createText(this._el_64,'One more separated link',(null as any));
    this._text_66 = this.renderer.createText(this._el_41,'\n          ',(null as any));
    this._text_67 = this.renderer.createText(this._el_36,'\n        ',(null as any));
    this._text_68 = this.renderer.createText(this._el_24,'\n      ',(null as any));
    this._text_69 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_22,'form',new import3.InlineArray2(2,'class','navbar-form navbar-left'),(null as any));
    this._NgForm_70_3 = new import13.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_70_4 = this._NgForm_70_3.context;
    this._NgControlStatusGroup_70_5 = new import14.Wrapper_NgControlStatusGroup(this._ControlContainer_70_4);
    this._text_71 = this.renderer.createText(this._el_70,'\n        ',(null as any));
    this._el_72 = import3.createRenderElement(this.renderer,this._el_70,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'\n          ',(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_72,'input',new import3.InlineArray8(6,'class','form-control','placeholder','Search','type','text'),(null as any));
    this._text_75 = this.renderer.createText(this._el_72,'\n        ',(null as any));
    this._text_76 = this.renderer.createText(this._el_70,'\n        ',(null as any));
    this._el_77 = import3.createRenderElement(this.renderer,this._el_70,'button',new import3.InlineArray4(4,'class','btn btn-default','type','submit'),(null as any));
    this._text_78 = this.renderer.createText(this._el_77,'Submit',(null as any));
    this._text_79 = this.renderer.createText(this._el_70,'\n      ',(null as any));
    this._text_80 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_81 = import3.createRenderElement(this.renderer,this._el_22,'ul',new import3.InlineArray2(2,'class','nav navbar-nav navbar-right'),(null as any));
    this._text_82 = this.renderer.createText(this._el_81,'\n        ',(null as any));
    this._el_83 = import3.createRenderElement(this.renderer,this._el_81,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._anchor_84 = this.renderer.createTemplateAnchor(this._el_83,(null as any));
    this._vc_84 = new import15.ViewContainer(84,83,this,this._anchor_84);
    this._TemplateRef_84_5 = new import21.TemplateRef_(this,84,this._anchor_84);
    this._NgIf_84_6 = new import16.Wrapper_NgIf(this._vc_84.vcRef,this._TemplateRef_84_5);
    this._text_85 = this.renderer.createText(this._el_81,'\n        ',(null as any));
    this._anchor_86 = this.renderer.createTemplateAnchor(this._el_81,(null as any));
    this._vc_86 = new import15.ViewContainer(86,81,this,this._anchor_86);
    this._TemplateRef_86_5 = new import21.TemplateRef_(this,86,this._anchor_86);
    this._NgIf_86_6 = new import16.Wrapper_NgIf(this._vc_86.vcRef,this._TemplateRef_86_5);
    this._text_87 = this.renderer.createText(this._el_81,'\n      ',(null as any));
    this._text_88 = this.renderer.createText(this._el_22,'\n    ',(null as any));
    this._text_89 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_90 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_91 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_6,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_6));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_36,new import3.InlineArray4(4,'keyup.esc',(null as any),'click','document'),this.eventHandler(this.handleEvent_36));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_38,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_38));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_70,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_70));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._el_83,
      this._anchor_84,
      this._text_85,
      this._anchor_86,
      this._text_87,
      this._text_88,
      this._text_89,
      this._text_90,
      this._text_91
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.NgbDropdownToggle) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._NgbDropdownToggle_38_3.context; }
    if (((token === import22.NgbDropdown) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._NgbDropdown_36_3.context; }
    if (((token === import23.NgForm) && ((70 <= requestNodeIndex) && (requestNodeIndex <= 79)))) { return this._NgForm_70_3.context; }
    if (((token === import24.ControlContainer) && ((70 <= requestNodeIndex) && (requestNodeIndex <= 79)))) { return this._ControlContainer_70_4; }
    if (((token === import25.NgControlStatusGroup) && ((70 <= requestNodeIndex) && (requestNodeIndex <= 79)))) { return this._NgControlStatusGroup_70_5.context; }
    if (((token === import21.TemplateRef) && (84 === requestNodeIndex))) { return this._TemplateRef_84_5; }
    if (((token === import26.NgIf) && (84 === requestNodeIndex))) { return this._NgIf_84_6.context; }
    if (((token === import21.TemplateRef) && (86 === requestNodeIndex))) { return this._TemplateRef_86_5; }
    if (((token === import26.NgIf) && (86 === requestNodeIndex))) { return this._NgIf_86_6.context; }
    if (((token === import27.NgClass) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 88)))) { return this._NgClass_22_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_22_0_0:any = 'collapse navbar-collapse';
    this._NgClass_22_3.check_klass(currVal_22_0_0,throwOnChange,false);
    const currVal_22_0_1:any = this._map_104(this.context.isIn);
    this._NgClass_22_3.check_ngClass(currVal_22_0_1,throwOnChange,false);
    this._NgClass_22_3.ngDoCheck(this,this._el_22,throwOnChange);
    this._NgbDropdown_36_3.ngDoCheck(this,this._el_36,throwOnChange);
    this._NgbDropdownToggle_38_3.ngDoCheck(this,this._el_38,throwOnChange);
    this._NgForm_70_3.ngDoCheck(this,this._el_70,throwOnChange);
    this._NgControlStatusGroup_70_5.ngDoCheck(this,this._el_70,throwOnChange);
    const currVal_84_0_0:boolean = !this.context.belongsToUser();
    this._NgIf_84_6.check_ngIf(currVal_84_0_0,throwOnChange,false);
    this._NgIf_84_6.ngDoCheck(this,this._anchor_84,throwOnChange);
    const currVal_86_0_0:any = this.context.belongsToUser();
    this._NgIf_86_6.check_ngIf(currVal_86_0_0,throwOnChange,false);
    this._NgIf_86_6.ngDoCheck(this,this._anchor_86,throwOnChange);
    this._vc_84.detectChangesInNestedViews(throwOnChange);
    this._vc_86.detectChangesInNestedViews(throwOnChange);
    this._NgbDropdown_36_3.checkHost(this,this,this._el_36,throwOnChange);
    this._NgbDropdownToggle_38_3.checkHost(this,this,this._el_38,throwOnChange);
    this._NgControlStatusGroup_70_5.checkHost(this,this,this._el_70,throwOnChange);
  }
  destroyInternal():void {
    this._vc_84.destroyNestedViews();
    this._vc_86.destroyNestedViews();
    this._NgbDropdown_36_3.ngOnDestroy();
    this._NgForm_70_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 84)) { return new View_HeaderComponent1(this.viewUtils,this,84,this._anchor_84,this._vc_84); }
    if ((nodeIndex == 86)) { return new View_HeaderComponent2(this.viewUtils,this,86,this._anchor_86,this._vc_86); }
    return (null as any);
  }
  handleEvent_6(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.toggleState()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_36(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgbDropdown_36_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_38(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgbDropdownToggle_38_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_70(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_70_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_HeaderComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import15.ViewContainer) {
    super(View_HeaderComponent1,renderType_HeaderComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'a',new import3.InlineArray2(2,'href','/auth'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'Login ',this.parentView.context.belongsToUser(),'');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_HeaderComponent2 extends import1.AppView<any> {
  _el_0:any;
  _NgbDropdown_0_3:import12.Wrapper_NgbDropdown;
  _text_1:any;
  _el_2:any;
  _NgbDropdownToggle_2_3:import12.Wrapper_NgbDropdownToggle;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import15.ViewContainer) {
    super(View_HeaderComponent2,renderType_HeaderComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',new import3.InlineArray4(4,'class','dropdown','ngbDropdown',''),(null as any));
    this._NgbDropdown_0_3 = new import12.Wrapper_NgbDropdown(this.parentView.parentView.injectorGet(import20.NgbDropdownConfig,this.parentView.parentIndex));
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray16(12,'aria-expanded','false','aria-haspopup','true','class','dropdown-toggle dropdown-toggle','data-toggle','dropdown','ngbDropdownToggle','','role','button'),(null as any));
    this._NgbDropdownToggle_2_3 = new import12.Wrapper_NgbDropdownToggle(this._NgbDropdown_0_3.context,new import19.ElementRef(this._el_2));
    this._text_3 = this.renderer.createText(this._el_2,'Profile ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'ul',new import3.InlineArray2(2,'class','dropdown-menu'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_7,'a',new import3.InlineArray2(2,'href','/profile'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Profile',(null as any));
    this._text_10 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_5,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_11,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Saved Jobs',(null as any));
    this._text_14 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_5,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_15,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Saved Blogs',(null as any));
    this._text_18 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_5,'li',new import3.InlineArray4(4,'class','divider','role','separator'),(null as any));
    this._text_20 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_5,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_21,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'Submit New',(null as any));
    this._text_24 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_5,'li',new import3.InlineArray4(4,'class','divider','role','separator'),(null as any));
    this._text_26 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_5,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_27,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Logout',(null as any));
    this._text_30 = this.renderer.createText(this._el_5,'\n          ',(null as any));
    this._text_31 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray4(4,'keyup.esc',(null as any),'click','document'),this.eventHandler(this.handleEvent_0));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_28,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_28));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.NgbDropdownToggle) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NgbDropdownToggle_2_3.context; }
    if (((token === import22.NgbDropdown) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NgbDropdown_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgbDropdown_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._NgbDropdownToggle_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgbDropdown_0_3.checkHost(this,this,this._el_0,throwOnChange);
    this._NgbDropdownToggle_2_3.checkHost(this,this,this._el_2,throwOnChange);
  }
  destroyInternal():void {
    this._NgbDropdown_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgbDropdown_0_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgbDropdownToggle_2_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_28(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onLogout()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}